// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
type CSSModuleClasses = { readonly [key: string]: string };
declare module '*.css' {
  const classes: CSSModuleClasses;
  export default classes;
}
declare module '*.scss' {
  const classes: CSSModuleClasses;
  export default classes;
}
declare module '*.sass' {
  const classes: CSSModuleClasses;
  export default classes;
}
declare module '*.less' {
  const classes: CSSModuleClasses;
  export default classes;
}
declare module '*.styl' {
  const classes: CSSModuleClasses;
  export default classes;
}
declare module '*.stylus' {
  const classes: CSSModuleClasses;
  export default classes;
}

// images
declare module '*.jpg' {
  const source: string;
  export default source;
}
declare module '*.jpeg' {
  const source: string;
  export default source;
}
declare module '*.png' {
  const source: string;
  export default source;
}
declare module '*.gif' {
  const source: string;
  export default source;
}
declare module '*.svg' {
  import * as React from 'react';

  export const ReactComponent: React.FunctionComponent<
    React.SVGProps<SVGSVGElement> & { title?: string }
  >;

  const source: string;
  export default source;
}
declare module '*.ico' {
  const source: string;
  export default source;
}
declare module '*.webp' {
  const source: string;
  export default source;
}
declare module '*.avif' {
  const source: string;
  export default source;
}

// media
declare module '*.mp4' {
  const source: string;
  export default source;
}
declare module '*.webm' {
  const source: string;
  export default source;
}
declare module '*.ogg' {
  const source: string;
  export default source;
}
declare module '*.mp3' {
  const source: string;
  export default source;
}
declare module '*.wav' {
  const source: string;
  export default source;
}
declare module '*.flac' {
  const source: string;
  export default source;
}
declare module '*.aac' {
  const source: string;
  export default source;
}

// fonts
declare module '*.woff' {
  const source: string;
  export default source;
}
declare module '*.woff2' {
  const source: string;
  export default source;
}
declare module '*.eot' {
  const source: string;
  export default source;
}
declare module '*.ttf' {
  const source: string;
  export default source;
}
declare module '*.otf' {
  const source: string;
  export default source;
}

// other
declare module '*.wasm' {
  const initWasm: (options: WebAssembly.Imports) => Promise<WebAssembly.Exports>;
  export default initWasm;
}
declare module '*.webmanifest' {
  const source: string;
  export default source;
}
declare module '*.pdf' {
  const source: string;
  export default source;
}
declare module '*.txt' {
  const source: string;
  export default source;
}
