name: Release CI
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.LOBEHUB_BOT_APP_ID }}
          private-key: ${{ secrets.LOBEHUB_BOT_APP_PRIVATE_KEY }}

      - uses: actions/checkout@v4

      - name: Install bun
        uses: oven-sh/setup-bun@v1

      - name: Install deps
        run: bun i

      - name: CI
        run: bun run ci

      - name: Test
        run: bun run test

      #      - name: Build
      #        run: bun run build

      - name: Release
        run: bun run release
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
